apiVersion: v1
kind: Service
metadata:
  name: {{ include "imposbro-search.fullname" . }}-admin-ui
  labels:
    {{- include "imposbro-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-ui
spec:
  type: {{ .Values.adminUi.service.type }}
  ports:
    - port: {{ .Values.adminUi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "imposbro-search.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin-ui
