{{- if .Values.secrets.externalSecret.enabled -}}
apiVersion: {{ .Values.secrets.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "imposbro-search.fullname" . }}-external-secret
  labels:
    {{- include "imposbro-search.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secrets.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.secrets.externalSecret.secretStoreRef.name | quote }}
    kind: {{ .Values.secrets.externalSecret.secretStoreRef.kind | quote }}
  target:
    name: {{ include "imposbro-search.secretName" . | quote }}
    creationPolicy: {{ .Values.secrets.externalSecret.target.creationPolicy }}
    deletionPolicy: {{ .Values.secrets.externalSecret.target.deletionPolicy }}
    template:
      metadata:
        {{- with .Values.secrets.externalSecret.target.template.metadata.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        labels:
          {{- include "imposbro-search.labels" . | nindent 10 }}
          {{- with .Values.secrets.externalSecret.target.template.metadata.labels }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
  {{- with .Values.secrets.externalSecret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.secrets.externalSecret.dataFrom }}
  dataFrom:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
