apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "imposbro-search.fullname" . }}-indexing-service
  labels:
    {{- include "imposbro-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: indexing-service
spec:
  {{- if and (not .Values.indexingService.autoscaling.enabled) (not .Values.indexingService.keda.enabled) }}
  replicas: {{ .Values.indexingService.replicaCount | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "imposbro-search.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: indexing-service
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "imposbro-search.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: indexing-service
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "imposbro-search.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.indexingService.name }}
          image: "{{ include "imposbro-search.requiredImage" (dict "name" "indexingService.image" "value" .Values.indexingService.image) }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.indexingService.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.indexingService.metrics.port }}
              protocol: TCP
          {{- end }}
          {{- with .Values.indexingService.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.indexingService.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "imposbro-search.fullname" . }}-config
            {{- if .Values.config.useSecret }}
            - secretRef:
                name: {{ include "imposbro-search.fullname" . }}-secret
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
