{{- if .Values.indexingService.autoscaling.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "imposbro-search.fullname" . }}-indexing-service
  labels:
    {{- include "imposbro-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: indexing-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "imposbro-search.fullname" . }}-indexing-service
  minReplicas: {{ .Values.indexingService.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.indexingService.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.indexingService.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.indexingService.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.indexingService.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.indexingService.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- with .Values.indexingService.autoscaling.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
