{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "imposbro-search.fullname" . }}-query-api
  labels:
    {{- include "imposbro-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: query-api
spec:
  podSelector:
    matchLabels:
      {{- include "imposbro-search.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: query-api
  policyTypes:
    - Ingress
    {{- with .Values.networkPolicy.queryApi.egress }}
    - Egress
    {{- end }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.queryApi.port }}
      {{- if or .Values.networkPolicy.queryApi.allowAdminUi .Values.networkPolicy.ingressController.from .Values.networkPolicy.queryApi.ingress.from (and .Values.monitoring.serviceMonitor.enabled .Values.monitoring.serviceMonitor.queryApi.enabled .Values.networkPolicy.prometheus.from) }}
      from:
        {{- if .Values.networkPolicy.queryApi.allowAdminUi }}
        - podSelector:
            matchLabels:
              {{- include "imposbro-search.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: admin-ui
        {{- end }}
        {{- if and .Values.monitoring.serviceMonitor.enabled .Values.monitoring.serviceMonitor.queryApi.enabled }}
        {{- with .Values.networkPolicy.prometheus.from }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- end }}
        {{- with .Values.networkPolicy.ingressController.from }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.networkPolicy.queryApi.ingress.from }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
  {{- with .Values.networkPolicy.queryApi.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "imposbro-search.fullname" . }}-admin-ui
  labels:
    {{- include "imposbro-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin-ui
spec:
  podSelector:
    matchLabels:
      {{- include "imposbro-search.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: admin-ui
  policyTypes:
    - Ingress
    {{- with .Values.networkPolicy.adminUi.egress }}
    - Egress
    {{- end }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.adminUi.port }}
      {{- if or .Values.networkPolicy.ingressController.from .Values.networkPolicy.adminUi.ingress.from }}
      from:
        {{- with .Values.networkPolicy.ingressController.from }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.networkPolicy.adminUi.ingress.from }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
  {{- with .Values.networkPolicy.adminUi.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if and .Values.indexingService.metrics.enabled .Values.indexingService.metrics.service.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "imposbro-search.fullname" . }}-indexing-service-metrics
  labels:
    {{- include "imposbro-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: indexing-service
spec:
  podSelector:
    matchLabels:
      {{- include "imposbro-search.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: indexing-service
  policyTypes:
    - Ingress
    {{- with .Values.networkPolicy.indexingService.egress }}
    - Egress
    {{- end }}
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.indexingService.metrics.port }}
      {{- if or .Values.networkPolicy.prometheus.from .Values.networkPolicy.indexingService.metrics.ingress.from }}
      from:
        {{- with .Values.networkPolicy.prometheus.from }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.networkPolicy.indexingService.metrics.ingress.from }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
  {{- with .Values.networkPolicy.indexingService.egress }}
  egress:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
