apiVersion: v1
kind: Service
metadata:
  name: {{ include "imposbro-search.fullname" . }}-query-api
  labels:
    {{- include "imposbro-search.labels" . | nindent 4 }}
    app.kubernetes.io/component: query-api
spec:
  type: {{ .Values.queryApi.service.type }}
  ports:
    - port: {{ .Values.queryApi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "imposbro-search.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: query-api
