global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'imposbro_services'
    static_configs:
      - targets: ['query_api:8000']
  - job_name: 'typesense'
    metrics_path: /metrics.json
    static_configs:
      - targets: ['typesense:8108', 'typesense-replica:8108']
