# Chart.yaml
apiVersion: v2
name: imposbro-search
description: A Helm chart for deploying the IMPOSBRO Search federated architecture on Kubernetes.
# A chart can be either an 'application' or a 'library' chart.
# 'application' is the default.
type: application

# This is the chart version. It should be incremented each time you make changes.
version: 0.1.0

# This is the version of the app that this chart deploys.
appVersion: "1.0.0"
