events {}

http {
  server {
    listen 8000;

    location / {
      resolver 127.0.0.11 valid=5s ipv6=off;
      set $query_api_upstream http://query_api:8000;
      proxy_pass $query_api_upstream;
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}

